services:
  iaeditais_db:
    image: pgvector/pgvector:pg17
    container_name: iaeditais_db
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: iaeditais
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - iaeditais_network

  iaeditais_api:
    image: gleidsoncosta/fiotec-iaeditais:latest
    container_name: iaeditais_api
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@iaeditais_db:5432/iaeditais
      BROKER_URL: amqp://guest:guest@iaeditais_rabbitmq:5672/
    volumes:
      - storage:/app/iaEditais/storage
    depends_on:
      - iaeditais_db
      - iaeditais_rabbitmq
    networks:
      - iaeditais_network

  iaeditais_redis:
    image: redis:latest
    container_name: iaeditais_redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - iaeditais_network

  iaeditais_rabbitmq:
    image: rabbitmq:latest
    container_name: iaeditais_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - iaeditais_network

  evolution_api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .evolution.env
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - iaeditais_network

volumes:
  dbdata:
  storage:
  cache:
  rabbitmq_data:
  evolution_instances:


networks:
  iaeditais_network:
    driver: bridge
